### ISSUE TITLE
Tests fail to compile with glibc 2.34

### ISSUE THREAD

**Issue by anujm1** [ospray/rkcommon#5]
```
/home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-skylake-64-altcfg/build/build/tmp/work/skylake-64-poky-linux/rkcommon/1.6.1-r0/git/tests/catch.hpp:10811:58: error: call to non-'constexpr' function 'long int sysconf(int)'
10811 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-skylake-64-altcfg/build/build/tmp/work/skylake-64-poky-linux/rkcommon/1.6.1-r0/recipe-sysroot/usr/include/bits/sigstksz.h:24,
                 from /home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-skylake-64-altcfg/build/build/tmp/work/skylake-64-poky-linux/rkcommon/1.6.1-r0/recipe-sysroot/usr/include/signal.h:328,
                 from /home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-skylake-64-altcfg/build/build/tmp/work/skylake-64-poky-linux/rkcommon/1.6.1-r0/git/tests/catch.hpp:8027,
                 from /home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-skylake-64-altcfg/build/build/tmp/work/skylake-64-poky-linux/rkcommon/1.6.1-r0/git/tests/catch_main.cpp:5:
/home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-skylake-64-altcfg/build/build/tmp/work/skylake-64-poky-linux/rkcommon/1.6.1-r0/recipe-sysroot/usr/include/unistd.h:641:17: note: 'long int sysconf(int)' declared here
  641 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-skylake-64-altcfg/build/build/tmp/work/skylake-64-poky-linux/rkcommon/1.6.1-r0/git/tests/catch_main.cpp:5:
/home/pokybuild/yocto-autobuilder-new/yocto-worker/intel-skylake-64-altcfg/build/build/tmp/work/skylake-64-poky-linux/rkcommon/1.6.1-r0/git/tests/catch.hpp:10870:45: error: size of array 'altStackMem' is not an integral constant-expression
10870 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
```

Looks like catch.hpp should be updated & regenerated to this version at least:

https://github.com/catchorg/Catch2/releases/tag/v2.13.5

which includes fix for:

https://github.com/catchorg/Catch2/issues/2178

**Comment by gregjohnson** [comment]
Thanks for reporting. We'll make this update.

**Comment by gregjohnson** [comment]
We've updated to the latest Catch2 now in `devel`: https://github.com/ospray/rkcommon/commit/1562d946a7d857701ffe956260a447473d954373

This change will be included in the next rkcommon release. Also, we're working to expand our internal testing to capture latest glibc / compiler versions, to better catch the issues.

Thanks again.
